name: Discord Notify

on:
  repository_dispatch:
    types: [discord_notify]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Check password and send message
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event.client_payload.password }}" != "$PASSWORD" ]; then
            echo "‚ùå Invalid password"
            exit 1
          fi

          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "Raid Dispatcher",
            "content": "'"${{ github.event.client_payload.message }}"'"
          }' $WEBHOOK_URL
